docker-compose.yml

Juri said:  
> I just had to modify two lines here and there to make old web dashboard work on my machine. It allows me to import projects to be analyzed.

Enable old-oss-web dashboard

---

docker-compose.yml
metric-platform/Dockerfile
metric-platform/wait-for-it.sh
oss-db/mongo-restore.sh

Fix to the OSS-BD container. Concurrent access during database restore created stability issues

Fix to oss-db crash at startup

---

docker-compose.yml
metric-platform/Dockerfile
metric-platform/META-INF/puppeteer.properties

Update of metric-platform environment to support the execution of the metric-providers of system configuration smells
Added Puppet support

System conf

---

KB-db/Dockerfile
KB-db/mongo-restore.sh

I have changed CROSSMINER kb dump. These changes support the integration between KB and IDE plugin.

Changed CROSSMINER KB dump

---

auth/application.properties
web-admin/Dockerfile
web-admin/default.conf

Fixed / Improvement:
- Fix  nginx 404 not found error for angular routing.

fix issue 404 not found nginx for angular routing

---

dashboard/starter.sh

This code prevents to constantly upload the web-based dashboards

[dashboard] Prevent periodical upload of dashboards

---

dashboard/Dockerfile
dashboard/importer-dashboards.sh
docker-compose-build.yml

This PR allows to set a default index pattern. It fixes #78 and should be reviewed together with https://github.com/crossminer/scava/pull/85

[dashboard] Fix default index

---

oss-db/mongo-restore.sh

Fix DB corruption on restart that was blocking the startup of the DB and all the containers that depend on it, like the auth-server #19

Fix oss db restart #19

---

dashboard/importer-scava-metrics.sh
docker-compose-build.yml

This PR allows to enable/disable the debug mode using an env variable defined
through the docker-compose-build.

[scava2es] debug flag

---

api-gw/application.properties

This PR fix the error 500 on 8086/administration/projects #74

Gateway zuul timeout

---

dashboard/importer-dashboards.sh
dashboard/importer-scava-metrics.sh

This PR replaces #37 and #38 to simplify testing. It must be reviewed with https://github.com/crossminer/scava/pull/136

[dashboards] Add dashboards 

---

docker-compose-build.yml

This code includes some new params for Prosoul which were needed to tackle the issue:
https://github.com/crossminer/scava-deployment/issues/44

[docker-compose-build] Update prosoul section

---

dashboard/importer-scava-metrics.sh

This code modifies the importer-scava-metrics.sh to import the configuration dependency data to elasticsearch.

[dashboard] Import configuration dependency data

---

dashboard/importer-dashboards.sh

This code changes the name of the sentiment dashboard, which is now scava-sentiment-emotion.json.

[dashboard] Rename sentiment dashboard

---

dashboard/importer-scava-metrics.sh

This code allows to import project relations to ES, thus enabling
the creation of visualizations.

[dashboard-importer] Import project relations data to ES

---

dashboard/Dockerfile
dashboard/importer-sonar-metrics.sh
dashboard/starter.sh

This code allows to automate the integration of sonarqube data to the scava-metrics index.

[Dashboard] Integrate sonarqube data

---

oss-db/mongo-restore.sh

We declare the pattern that match the dump files to restore. Then we iterate over those files and mongorestore.

loop for restoring dumps

---

dashboard/Dockerfile
dashboard/importer-omm-metrics.sh
dashboard/starter.sh

This PR allows to fetch OMM data from one or more remote URLs.

[dahsboar] Add support to fetch OMM data

---

README.md

This PR includes some information to speed up the build and make sure to start from a fresh env/installation

[doc] Add docker-compose issue section

---

README.md

related to https://github.com/crossminer/scava-deployment/issues/89

[doc] Add task analysis section in README.md

---

dashboard/importer-dashboards.sh

This code includes an initial version of the scava code dashboard, which currently includes 2 visualizations to select projects and top projects plus 2 more visualizations to show the evolution of API changes and API breaking changes.

[dashboard] Add scava code dashboard
